/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
// heredar de la clase thread 


class Hilo  extends Thread {
    public String cadena;
    Hilo( String cadena){
        this.cadena = cadena;
    }

    public void run()
    {
        System.out.print(cadena);
    }
}

class HolaMundo{
    public static void main(String[] args)
    {
        Hilo h1=new Hilo(" Hola ");
        Hilo h2=new Hilo(" Mundo ");
        Hilo h3=new Hilo(" como ");
        Hilo h4=new Hilo(" estas ?");

        h1.start();
        h2.start();
        h3.start();
        h4.start();
        //System.out.println ("Yo soy el main...");
        
        try{
        h1.join();
        h2.join();
        h3.join();
        h4.join();

        }catch(InterruptedException e) {}
        
        System.exit(0);
    }

}
